spring:
  main:
    banner-mode: "off"
  application:
    name: conference-app
  display-name: conference-app

  h2:
    console:
      enabled: true

  liquibase:
    url: jdbc:h2:./data/app;AUTO_SERVER=true

  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase

togglz:
  enabled: true
  feature-enums: com.github.catalin.cretu.conference.togglz.FeatureToggle
  console:
    enabled: true
    secured: false
    use-management-port: false