spring:
  main:
    banner-mode: "off"
  application:
    name: conference-app
  display-name: conference-app

  h2:
    console:
      enabled: true

  liquibase:
    url: jdbc:h2:./data/app;AUTO_SERVER=true

  compression:
    enabled: true

management:
  health:
    db:
      enabled: false